# Generated by Django 6.0.3 on 2026-05-05 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0003_project_creator_favorite_projectrating_projectreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrating',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rated', to='diyprojects.project'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed', to='diyprojects.project'),
        ),
    ]
