# Generated by Django 6.0.2 on 2026-05-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchstore', '0005_alter_product_id_alter_producttype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='merchstore/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On sale', 'On sale'), ('Out of stock', 'Out of stock')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('On cart', 'On cart'), ('To Pay', 'To Pay'), ('To Ship', 'To Ship'), ('To Receive', 'To Receive'), ('Delivered', 'Delivered')], default='On cart', max_length=20),
        ),
    ]
