# Generated by Django 5.2.11 on 2026-03-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_year']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
