# Generated by Django 5.2.11 on 2026-05-07 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookclub', '0005_alter_book_contributor_alter_book_publication_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='user_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to='accounts.profile'),
        ),
    ]
