# Generated by Django 6.0.1 on 2026-03-05 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commissions",
            options={"ordering": ["created_on"], "verbose_name_plural": "Commissions"},
        ),
        migrations.AlterModelOptions(
            name="commissiontype",
            options={"ordering": ["name"], "verbose_name_plural": "Commission Types"},
        ),
    ]
